In [1]:
#England Premier League

import pandas as pd
import requests

#2022-2023 
url = 'https://fbref.com/en/comps/9/2022-2023/stats/2022-2023-Premier-League-Stats'
    
response = requests.get(url).text.replace('<!--', '').replace('-->', '')
df_Players_Standard_Stats_England_Premier_League = pd.read_html(response, header=1)[2]


# Add a new column for the league name
df_Players_Standard_Stats_England_Premier_League['Country'] = 'England Premier League'
df_Players_Standard_Stats_England_Premier_League['Season'] = '2022-2023'

In [2]:
df = df_Players_Standard_Stats_England_Premier_League

In [3]:
# Normalize player names using the unidecode function
from unidecode import unidecode
df["Player"] = df["Player"].apply(unidecode)

In [4]:
# Remove the country codes from the team names
df['Nation'] = df['Nation'].astype(str).apply(lambda x: x.split()[1:] if len(x.split())>1 else x)
df['Nation'] = df['Nation'].apply(lambda x: ' '.join(x))

In [5]:
# Remove dublicate head name
df = df.drop(df[df['Rk'] == 'Rk'].index)

In [6]:
# Remove columns 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK', 'xG.1', 'xAG.1', 'xG+xAG', 'npxG.1', 'npxG+xAG.1', 'Matches'
df.drop(['npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK', 'xG.1', 'xAG.1', 'xG+xAG', 'npxG.1', 'npxG+xAG.1', 'Matches'], axis=1, inplace=True)

In [7]:
df

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,Country,Season
0,1,Brenden Aaronson,USA,"MF,FW",Leeds United,21,2000,36,28,2372,...,3,4,1,0,0,2,0,3.9,England Premier League,2022-2023
1,2,George Abbott,ENG,MF,Tottenham,16,2005,1,0,1,...,0,0,0,0,0,0,0,0.0,England Premier League,2022-2023
2,3,Che Adams,SCO,FW,Southampton,26,1996,28,23,1992,...,3,8,5,0,0,1,0,6.6,England Premier League,2022-2023
3,4,Tyler Adams,USA,MF,Leeds United,23,1999,24,24,2156,...,0,0,0,0,0,6,1,0.1,England Premier League,2022-2023
4,5,Tosin Adarabioyo,ENG,DF,Fulham,24,1997,25,23,2085,...,0,1,1,0,0,4,0,0.7,England Premier League,2022-2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,565,Jordan Zemura,ZIM,DF,Bournemouth,22,1999,19,17,1454,...,1,1,0,0,0,1,0,0.4,England Premier League,2022-2023
587,566,Oleksandr Zinchenko,UKR,DF,Arsenal,25,1996,27,26,2118,...,2,3,1,0,0,3,0,1.4,England Premier League,2022-2023
588,567,Hakim Ziyech,MAR,"FW,MF",Chelsea,29,1993,18,6,661,...,3,3,0,0,0,1,0,0.6,England Premier League,2022-2023
589,568,Kurt Zouma,FRA,DF,West Ham,27,1994,25,24,1989,...,0,2,2,0,0,0,0,2.2,England Premier League,2022-2023
590,569,Martin Odegaard,NOR,MF,Arsenal,23,1998,37,37,3127,...,7,22,15,0,0,4,0,10.0,England Premier League,2022-2023

In [8]:
df.to_csv('England Premier League Players 2022-2023.csv', index=False)